# Site settings
title: EdgeML
email: 
description: > 
  Project page for EdgeML
# Comment baseurl out when editing locally
#baseurl: "https://microsoft.github.io/EdgeML"
url: "https://microsoft.github.io/EdgeML"

# Build settings
markdown: kramdown
port: 4000
host: localhost

collections:
  Blog:
    output: true
    permalink: /:collection/:name

exclude: [archive]
